name: build xiaomi 4c

on:
  workflow_dispatch:
  release:
    types: [published]  
    
jobs:
  download-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download files
      run: |
        sudo apt update
        sudo apt install build-essential file libncurses-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip python3 python3-full python3-venv -y
        mkdir -p downloads
        cd downloads
        wget https://archive.openwrt.org/releases/24.10.3/targets/ramips/mt76x8/openwrt-imagebuilder-24.10.3-ramips-mt76x8.Linux-x86_64.tar.zst
        tar --zstd -xvf openwrt-imagebuilder-*.tar.zst
        cd openwrt-imagebuilder-*/
        make image PROFILE="xiaomi_mi-router-4c" PACKAGES="base-files ca-bundle dropbear firewall4 fstools kmod-gpio-button-hotplug kmod-leds-gpio kmod-mt7603 kmod-nft-offload libc libgcc libustream-wolfssl logd mtd netifd nftables odhcp6c odhcpd-ipv6only opkg ppp ppp-mod-pppoe swconfig uci uclient-fetch urandom-seed urngd wpad-basic-wolfssl uboot-envtools luci kmod-mt76 kmod-mtd-rw dnsmasq iw-full ip-full ethtool-full UDPspeeder zram-swap nano"
        
    - name: Create and push tag
      id: tag_version
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          VERSION="${{ github.event.release.tag_name }}"
        else
          VERSION="openwrt-24.10.3-xiaomi-4c"
        fi
        
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag -a "$VERSION" -m "Release $VERSION"
        git push origin "$VERSION"
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Delete existing release assets
      uses: actions/github-script@v7
      with:
        script: |
          const { data: assets } = await github.rest.repos.listReleaseAssets({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: context.payload.release.id
          });
          
          for (const asset of assets) {
            await github.rest.repos.deleteReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              asset_id: asset.id
            });
          }
      if: github.event_name == 'release'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload files to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag_version.outputs.version }}
        files: |
          downloads/openwrt-imagebuilder-24.10.3-ramips-mt76x8.Linux-x86_64/bin/targets/ramips/mt76x8/*.bin
        overwrite: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
